name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install mlflow
      - name: Start a local server
        run: mlflow server
      - name: Run tests against the server
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: curl http://localhost:5000

